# Site settings
title: Suninvest
description: Suninvest D.O.O. Official Website
email: support@suninvest.org

# Google-analytics
google-analytics:
  id: "UA-113235994-1"

compress:
  js: '/assets/js/*.js'
  css: '/assets/styles/*.css'
  img: '/assets/**/*.{jpg,png}'
