# Site settings
title: Suninvest
description: Suninvest D.O.O. Official Website
email: support@suninvest.org

compress:
  js: '/assets/js/*.js'
  css: '/assets/styles/*.css'
  img: '/assets/**/*.{jpg,png}'
